"""empty message

Revision ID: a3d422fcee49
Revises: 
Create Date: 2023-05-10 19:31:03.576475

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3d422fcee49'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('likea_perfil',
    sa.Column('id_usuario', sa.String(length=50), nullable=False),
    sa.Column('id_usuario2', sa.String(length=50), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id_usuario', 'id_usuario2')
    )
    op.create_table('likea_publicacion',
    sa.Column('id_usuario', sa.String(length=50), nullable=False),
    sa.Column('id_usuario2', sa.String(length=50), nullable=False),
    sa.Column('id_publicacion', sa.String(length=36), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id_usuario', 'id_usuario2', 'id_publicacion')
    )
    op.create_table('perfil',
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('nacimiento', sa.Date(), nullable=False),
    sa.Column('edad', sa.Integer(), nullable=False),
    sa.Column('genero', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sa.String(length=500), nullable=True),
    sa.Column('ruta_photo', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.Date(), nullable=True),
    sa.Column('modified_at', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('username')
    )
    op.create_table('post',
    sa.Column('id_publicacion', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id_publicacion')
    )
    op.create_table('suscripcion',
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('precio', sa.Float(), nullable=False),
    sa.Column('created', sa.Date(), nullable=True),
    sa.Column('modified', sa.Date(), nullable=True),
    sa.Column('day_duration', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('nombre')
    )
    op.create_table('usuario',
    sa.Column('id_usuario', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=36), nullable=True),
    sa.Column('correo', sa.String(length=50), nullable=False),
    sa.Column('contraseña', sa.String(length=100), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('likes_restantes', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['username'], ['perfil.username'], ),
    sa.PrimaryKeyConstraint('id_usuario')
    )
    op.create_table('compra',
    sa.Column('id_compra', sa.String(length=36), nullable=False),
    sa.Column('id_usuario', sa.String(length=50), nullable=True),
    sa.Column('nombre_suscripcion', sa.String(length=50), nullable=True),
    sa.Column('fecha', sa.Date(), nullable=True),
    sa.Column('precio_compra', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id_usuario'], ),
    sa.ForeignKeyConstraint(['nombre_suscripcion'], ['suscripcion.nombre'], ),
    sa.PrimaryKeyConstraint('id_compra')
    )
    op.create_table('mensaje',
    sa.Column('id_mensaje', sa.String(length=36), nullable=False),
    sa.Column('id_usuariodestinatario', sa.String(length=50), nullable=True),
    sa.Column('id_usuarioremitente', sa.String(length=50), nullable=True),
    sa.Column('id_mensaje2', sa.String(length=36), nullable=True),
    sa.Column('fecha', sa.Date(), nullable=True),
    sa.Column('contenido', sa.String(length=500), nullable=True),
    sa.Column('state', sa.String(length=50), nullable=True),
    sa.Column('formato', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['id_mensaje2'], ['mensaje.id_mensaje'], ),
    sa.ForeignKeyConstraint(['id_usuariodestinatario'], ['usuario.id_usuario'], ),
    sa.ForeignKeyConstraint(['id_usuarioremitente'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_mensaje')
    )
    op.create_table('publicacion',
    sa.Column('id_publicacion', sa.String(length=36), nullable=False),
    sa.Column('id_usuario', sa.String(length=50), nullable=True),
    sa.Column('contenido', sa.String(length=500), nullable=True),
    sa.Column('modified_at', sa.Date(), nullable=True),
    sa.Column('created_at', sa.Date(), nullable=True),
    sa.Column('cantidad_likes', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_publicacion')
    )
    op.create_table('comentario',
    sa.Column('id_publicacion', sa.String(length=36), nullable=False),
    sa.Column('id_publicacion2', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['id_publicacion2'], ['publicacion.id_publicacion'], ),
    sa.PrimaryKeyConstraint('id_publicacion')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comentario')
    op.drop_table('publicacion')
    op.drop_table('mensaje')
    op.drop_table('compra')
    op.drop_table('usuario')
    op.drop_table('suscripcion')
    op.drop_table('post')
    op.drop_table('perfil')
    op.drop_table('likea_publicacion')
    op.drop_table('likea_perfil')
    # ### end Alembic commands ###
