"""empty message

Revision ID: d4dc20757dd4
Revises: ec5ed85a72bc
Create Date: 2023-05-12 16:12:00.775713

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4dc20757dd4'
down_revision = 'ec5ed85a72bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('my_model')
    with op.batch_alter_table('perfil', schema=None) as batch_op:
        batch_op.alter_column('genero',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('perfil', schema=None) as batch_op:
        batch_op.alter_column('genero',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)

    op.create_table('my_model',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('param_str', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('param_int', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('param_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('param_image_route', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('param_gender', sa.VARCHAR(length=1), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='my_model_pkey')
    )
    # ### end Alembic commands ###
